apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv 
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Block
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Can be mounted as a read write volume on a single node
    # - ReadOnlyMany # Read only but can be claimed by multiple nodes; not available for hostPath
    # - ReadWriteMany # not available for hostPath
  hostPath: 
    path: /data
    type: DirectoryOrCreate